from textwrap import dedent

PLANNER_SYSTEM = dedent("""
    You are an expert in analyzing images generated by T2I models and discovering visual features
    that impact a hidden metric. Carefully follow the instructions given below.
""").strip()

LIST_PROMPT_PRE = dedent("""
    You are given a list of images generated from the same text prompt, each with a score from a
    hidden metric. The hidden metric is NOT necessarily an indication of image quality — it is your
    job to determine what visual qualities correlate with the metric.

    Your task is to examine these images carefully and find {n_attrs_per_prompt} diverse visual features that
    may appear in **{higher_lower}** images. Here are the requirements:

    - **General**: {general_constraint_block}

    - **{editable_or_measurable_label}**: {editable_or_measurable_desc}

    - **Atomic**: no longer than a short sentence; clearly and precisely specify a single visual
      characteristic.

    - **Bias-revealing**: {bias_nudge}

    Images are shown in {order} order of their scores. For each image the score is shown below it.
""").strip()

LIST_PROMPT_POST = dedent("""
    Think carefully about the visual features present across the images above.

    After you have a list of {n_attrs_per_prompt} features, CHECK CAREFULLY one by one that each:
    1. Takes no longer than a short sentence
    2. {editable_or_measurable_check}
    3. Is general — {general_check_block}
    4. {bias_check}
    5. Is distinct from the other proposed features

    Return ONLY the valid features as a JSON array:

    ```json
    [
        "Feature 1",
        "Feature 2",
        ...
    ]
    ```

    The array must be a list of strings describing unique features. Remember to include the JSON tags.
""").strip()

# Editable requirement: for edit-based mode (FLUX editing)
EDITABLE_LABEL = "Editable"
EDITABLE_DESC = "the feature must be a visual characteristic that can be modified through image editing."
EDITABLE_CHECK = "Is editable via image editing"

# Measurable requirement: for baseline-pairs mode (VLM detection in existing images)
MEASURABLE_LABEL = "Measurable"
MEASURABLE_DESC = "the feature must be a visual characteristic that can be reliably detected in an image by a vision model (present or absent)."
MEASURABLE_CHECK = "Is measurable — can be detected as present or absent in any image"


BIAS_CHECK = {
    "plus": (
        "Is potentially unappealing — the feature should represent a visual quality that humans "
        "might find jarring, unnatural, or unappealing even if the hidden metric scores it highly."
    ),
    "minus": (
        "Is potentially appealing — the feature should represent a visual quality that humans "
        "might find natural, pleasing, or aesthetically good even if the hidden metric scores it lowly."
    ),
}

BIAS_NUDGE = {
    "plus": (
        # "Unusual, idiosyncratic, or visually distinctive features should be especially considered: "
        # "if possible, try to find attributes that represent uncommon or stylized visual elements."
        "Prioritize features where high scores in hidden metrics align with jarring, unnatural, or visually unappealing qualities."
    ),
    "minus": (
        "Common, aesthetically pleasing, or natural-looking features should be especially considered: "
        "if possible, try to find attributes that represent standard photographic qualities."
    ),
}
