from textwrap import dedent

PLANNER_SYSTEM = dedent("""
    You are an expert in analyzing images generated by T2I models and discovering visual features
    that impact a hidden metric. Carefully follow the instructions given below.
""").strip()

LIST_PROMPT_PRE = dedent("""
    You are given a list of images generated from the same text prompt, each with a score from a
    hidden metric. The hidden metric is NOT necessarily an indication of image quality — it is your
    job to determine what visual qualities correlate with the metric.

    Your task is to examine these images carefully and find {n_attrs_per_prompt} diverse visual features that
    may appear in **{higher_lower}** images. Here are the requirements:

    - **General**: {general_constraint_block}

    - **Editable**: the feature must be a visual characteristic that can be modified through image
      editing.

    - **Atomic**: no longer than a short sentence; clearly and precisely specify a single visual
      characteristic.

    Images are shown in {order} order of their scores. For each image the score is shown below it.
""").strip()

LIST_PROMPT_POST = dedent("""
    Think carefully about the visual features present across the images above. Consider both
    high-level properties (color scheme, lighting, composition) and low-level properties
    (saturation, brightness, contrast). {bias_nudge}

    After you have a list of {n_attrs_per_prompt} features, CHECK CAREFULLY one by one that each:
    1. Takes no longer than a short sentence
    2. Is editable via image editing
    3. Is general — {general_check_block}
    4. Is distinct from the other proposed features

    Return ONLY the valid features as a JSON array:

    ```json
    [
        "Feature 1",
        "Feature 2",
        ...
    ]
    ```

    The array must be a list of strings describing unique features. Remember to include the JSON tags.
""").strip()

BIAS_NUDGE = {
    "plus": (
        # "Unusual, idiosyncratic, or visually distinctive features should be especially considered: "
        # "if possible, try to find attributes that represent uncommon or stylized visual elements."
        "Prioritize features where high scores in hidden metrics align with jarring, unnatural, or visually unappealing qualities."
    ),
    "minus": (
        "Common, aesthetically pleasing, or natural-looking features should be especially considered: "
        "if possible, try to find attributes that represent standard photographic qualities."
    ),
}
